# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "tl128"
    name       = "特零128小站"
    url        = "https://tl128.hubingsf.cn/"

    [social.params]
        icon = "star"

[[social]]
    identifier = "dark-coffin"
    name       = "黑柩创作站"
    url        = "https://darkcoffin.hubingsf.cn"

    [social.params]
        icon = "dark-coffin"
